# Generated by Django 5.2.8 on 2025-11-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicacao",
            name="latitude",
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name="publicacao",
            name="longitude",
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
    ]
