# Generated by Django 5.2.8 on 2025-11-16 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0002_avaliacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacao",
            name="publicacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avaliacoes",
                to="usuario.publicacao",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacao",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avaliacoes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="imagem",
            name="publicacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imagens",
                to="usuario.publicacao",
            ),
        ),
    ]
