# Generated by Django 5.2.8 on 2025-12-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0002_alter_publicacao_latitude_alter_publicacao_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacao",
            name="avaliacao",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=2, null=True
            ),
        ),
    ]
