# Generated by Django 5.2.8 on 2025-12-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0003_alter_avaliacao_avaliacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacao",
            name="data_criacao",
            field=models.DateTimeField(
                auto_now_add=True, default="2025-01-15 00:00:00"
            ),
            preserve_default=False,
        ),
    ]
