# Generated by Django 5.2.8 on 2025-11-16 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0003_alter_avaliacao_publicacao_alter_avaliacao_usuario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicacao",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publicacoes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
