# Generated by Django 5.2.8 on 2025-12-09 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0004_avaliacao_data_criacao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="avaliacao",
            options={"ordering": ["-data_criacao"]},
        ),
    ]
