# Generated by Django 5.2.8 on 2025-11-17 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0004_alter_publicacao_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagem",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="imagem",
            name="arquivo",
            field=models.ImageField(upload_to="publicacoes/"),
        ),
    ]
