# Generated by Django 5.2.8 on 2025-11-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0005_imagem_usuario_alter_imagem_arquivo"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicacao",
            name="endereco",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="publicacao",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="publicacao",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="publicacao",
            name="titulo",
            field=models.CharField(default="", max_length=150),
        ),
    ]
