# Generated by Django 5.2.8 on 2025-11-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0006_publicacao_endereco_publicacao_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagem",
            name="is_principal",
            field=models.BooleanField(default=False),
        ),
    ]
