# Generated by Django 5.2.8 on 2025-11-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0007_imagem_is_principal"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicacao",
            name="especificacao_rota",
            field=models.CharField(default="", max_length=250),
        ),
    ]
